version: 2
jobs:
  build:        
    filters:
      tags:
        only: /^\d+\.\d+\.\d+$/
    working_directory: ~/gath
    environment:      
      _JAVA_OPTIONS: "-Xmx3g -Djdk.module.illegalAccess=deny"
      _JAVAC_OPTIONS: "-Xlint:unchecked -Xlint:deprecation"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps: 
      - checkout       
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - run:
          name: ensure gradlew is executable...
          command: chmod +x ./gradlew
      - run:
          name: Starting real build process...
          command: |
            echo "There we go..."
            ./gradlew build

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
